# Database settings.
database:

  # the name of your JDBC driver
  #driverClass: org.hsqldb.jdbcDriver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password:

  logValidationErrors: false
  #validationQuery: SELECT * FROM INFORMATION_SCHEMA.SYSTEM_TABLES

  # the JDBC URL
  #url: jdbc:hsqldb:mem:test
  url: jdbc:h2:./data/kwikshop-db

  properties:
    #hibernate.dialect: org.hibernate.dialect.HSQLDialect
    hibernate.dialect: org.hibernate.dialect.H2Dialect

    #TODO flip to validate on server
    hibernate.hbm2ddl.auto: 'update'

#logging:
#    level: DEBUG

server:
  requestLog:
    timeZone: UTC
    appenders:
      - type: console
  applicationConnectors:
    - type: https
      port: 443
      keyStorePath: ./data/keystore.jks
      keyStorePassword: ${KEYSTORE_PW}
      validateCerts: false
